// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMsg.proto

package com.xirui.protocol;

public final class BaseProtos {
  private BaseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xirui.protocol.BaseMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 字段格式为：限定修饰符 数据类型 字段名称(建议以_分隔) = 分配标识号(同一消息结构体中不能重复，无须连续，开始使用就不能再改变)
     * </pre>
     *
     * <code>uint32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
     * @return Whether the msg field is set.
     */
    boolean hasMsg();
    /**
     * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
     * @return The msg.
     */
    com.xirui.protocol.BaseProtos.Msg1 getMsg();
    /**
     * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
     */
    com.xirui.protocol.BaseProtos.Msg1OrBuilder getMsgOrBuilder();
  }
  /**
   * <pre>
   * 消息定义
   * </pre>
   *
   * Protobuf type {@code com.xirui.protocol.BaseMsg}
   */
  public static final class BaseMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xirui.protocol.BaseMsg)
      BaseMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseMsg.newBuilder() to construct.
    private BaseMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseMsg() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BaseMsg();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xirui.protocol.BaseProtos.internal_static_com_xirui_protocol_BaseMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xirui.protocol.BaseProtos.internal_static_com_xirui_protocol_BaseMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xirui.protocol.BaseProtos.BaseMsg.class, com.xirui.protocol.BaseProtos.BaseMsg.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_ = 0;
    /**
     * <pre>
     * 字段格式为：限定修饰符 数据类型 字段名称(建议以_分隔) = 分配标识号(同一消息结构体中不能重复，无须连续，开始使用就不能再改变)
     * </pre>
     *
     * <code>uint32 type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private com.xirui.protocol.BaseProtos.Msg1 msg_;
    /**
     * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return msg_ != null;
    }
    /**
     * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
     * @return The msg.
     */
    @java.lang.Override
    public com.xirui.protocol.BaseProtos.Msg1 getMsg() {
      return msg_ == null ? com.xirui.protocol.BaseProtos.Msg1.getDefaultInstance() : msg_;
    }
    /**
     * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
     */
    @java.lang.Override
    public com.xirui.protocol.BaseProtos.Msg1OrBuilder getMsgOrBuilder() {
      return msg_ == null ? com.xirui.protocol.BaseProtos.Msg1.getDefaultInstance() : msg_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeUInt32(1, type_);
      }
      if (msg_ != null) {
        output.writeMessage(2, getMsg());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, type_);
      }
      if (msg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMsg());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xirui.protocol.BaseProtos.BaseMsg)) {
        return super.equals(obj);
      }
      com.xirui.protocol.BaseProtos.BaseMsg other = (com.xirui.protocol.BaseProtos.BaseMsg) obj;

      if (getType()
          != other.getType()) return false;
      if (hasMsg() != other.hasMsg()) return false;
      if (hasMsg()) {
        if (!getMsg()
            .equals(other.getMsg())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xirui.protocol.BaseProtos.BaseMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xirui.protocol.BaseProtos.BaseMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xirui.protocol.BaseProtos.BaseMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xirui.protocol.BaseProtos.BaseMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xirui.protocol.BaseProtos.BaseMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xirui.protocol.BaseProtos.BaseMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xirui.protocol.BaseProtos.BaseMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xirui.protocol.BaseProtos.BaseMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.xirui.protocol.BaseProtos.BaseMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.xirui.protocol.BaseProtos.BaseMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xirui.protocol.BaseProtos.BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xirui.protocol.BaseProtos.BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xirui.protocol.BaseProtos.BaseMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 消息定义
     * </pre>
     *
     * Protobuf type {@code com.xirui.protocol.BaseMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xirui.protocol.BaseMsg)
        com.xirui.protocol.BaseProtos.BaseMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xirui.protocol.BaseProtos.internal_static_com_xirui_protocol_BaseMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xirui.protocol.BaseProtos.internal_static_com_xirui_protocol_BaseMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xirui.protocol.BaseProtos.BaseMsg.class, com.xirui.protocol.BaseProtos.BaseMsg.Builder.class);
      }

      // Construct using com.xirui.protocol.BaseProtos.BaseMsg.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = 0;
        msg_ = null;
        if (msgBuilder_ != null) {
          msgBuilder_.dispose();
          msgBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xirui.protocol.BaseProtos.internal_static_com_xirui_protocol_BaseMsg_descriptor;
      }

      @java.lang.Override
      public com.xirui.protocol.BaseProtos.BaseMsg getDefaultInstanceForType() {
        return com.xirui.protocol.BaseProtos.BaseMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.xirui.protocol.BaseProtos.BaseMsg build() {
        com.xirui.protocol.BaseProtos.BaseMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xirui.protocol.BaseProtos.BaseMsg buildPartial() {
        com.xirui.protocol.BaseProtos.BaseMsg result = new com.xirui.protocol.BaseProtos.BaseMsg(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.xirui.protocol.BaseProtos.BaseMsg result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.msg_ = msgBuilder_ == null
              ? msg_
              : msgBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xirui.protocol.BaseProtos.BaseMsg) {
          return mergeFrom((com.xirui.protocol.BaseProtos.BaseMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xirui.protocol.BaseProtos.BaseMsg other) {
        if (other == com.xirui.protocol.BaseProtos.BaseMsg.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                type_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getMsgFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <pre>
       * 字段格式为：限定修饰符 数据类型 字段名称(建议以_分隔) = 分配标识号(同一消息结构体中不能重复，无须连续，开始使用就不能再改变)
       * </pre>
       *
       * <code>uint32 type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 字段格式为：限定修饰符 数据类型 字段名称(建议以_分隔) = 分配标识号(同一消息结构体中不能重复，无须连续，开始使用就不能再改变)
       * </pre>
       *
       * <code>uint32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {

        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字段格式为：限定修饰符 数据类型 字段名称(建议以_分隔) = 分配标识号(同一消息结构体中不能重复，无须连续，开始使用就不能再改变)
       * </pre>
       *
       * <code>uint32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.xirui.protocol.BaseProtos.Msg1 msg_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xirui.protocol.BaseProtos.Msg1, com.xirui.protocol.BaseProtos.Msg1.Builder, com.xirui.protocol.BaseProtos.Msg1OrBuilder> msgBuilder_;
      /**
       * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
       * @return Whether the msg field is set.
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
       * @return The msg.
       */
      public com.xirui.protocol.BaseProtos.Msg1 getMsg() {
        if (msgBuilder_ == null) {
          return msg_ == null ? com.xirui.protocol.BaseProtos.Msg1.getDefaultInstance() : msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
       */
      public Builder setMsg(com.xirui.protocol.BaseProtos.Msg1 value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
        } else {
          msgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
       */
      public Builder setMsg(
          com.xirui.protocol.BaseProtos.Msg1.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
       */
      public Builder mergeMsg(com.xirui.protocol.BaseProtos.Msg1 value) {
        if (msgBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            msg_ != null &&
            msg_ != com.xirui.protocol.BaseProtos.Msg1.getDefaultInstance()) {
            getMsgBuilder().mergeFrom(value);
          } else {
            msg_ = value;
          }
        } else {
          msgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = null;
        if (msgBuilder_ != null) {
          msgBuilder_.dispose();
          msgBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
       */
      public com.xirui.protocol.BaseProtos.Msg1.Builder getMsgBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
       */
      public com.xirui.protocol.BaseProtos.Msg1OrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_ == null ?
              com.xirui.protocol.BaseProtos.Msg1.getDefaultInstance() : msg_;
        }
      }
      /**
       * <code>.com.xirui.protocol.Msg1 msg = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xirui.protocol.BaseProtos.Msg1, com.xirui.protocol.BaseProtos.Msg1.Builder, com.xirui.protocol.BaseProtos.Msg1OrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.xirui.protocol.BaseProtos.Msg1, com.xirui.protocol.BaseProtos.Msg1.Builder, com.xirui.protocol.BaseProtos.Msg1OrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xirui.protocol.BaseMsg)
    }

    // @@protoc_insertion_point(class_scope:com.xirui.protocol.BaseMsg)
    private static final com.xirui.protocol.BaseProtos.BaseMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xirui.protocol.BaseProtos.BaseMsg();
    }

    public static com.xirui.protocol.BaseProtos.BaseMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMsg>
        PARSER = new com.google.protobuf.AbstractParser<BaseMsg>() {
      @java.lang.Override
      public BaseMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BaseMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xirui.protocol.BaseProtos.BaseMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Msg1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xirui.protocol.Msg1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 字段格式为：限定修饰符 数据类型 字段名称(建议以_分隔) = 分配标识号(同一消息结构体中不能重复，无须连续，开始使用就不能再改变)
     * </pre>
     *
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>bool b = 3;</code>
     * @return The b.
     */
    boolean getB();

    /**
     * <code>string des = 4;</code>
     * @return The des.
     */
    java.lang.String getDes();
    /**
     * <code>string des = 4;</code>
     * @return The bytes for des.
     */
    com.google.protobuf.ByteString
        getDesBytes();
  }
  /**
   * Protobuf type {@code com.xirui.protocol.Msg1}
   */
  public static final class Msg1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xirui.protocol.Msg1)
      Msg1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg1.newBuilder() to construct.
    private Msg1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg1() {
      content_ = "";
      des_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Msg1();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xirui.protocol.BaseProtos.internal_static_com_xirui_protocol_Msg1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xirui.protocol.BaseProtos.internal_static_com_xirui_protocol_Msg1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xirui.protocol.BaseProtos.Msg1.class, com.xirui.protocol.BaseProtos.Msg1.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <pre>
     * 字段格式为：限定修饰符 数据类型 字段名称(建议以_分隔) = 分配标识号(同一消息结构体中不能重复，无须连续，开始使用就不能再改变)
     * </pre>
     *
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";
    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int B_FIELD_NUMBER = 3;
    private boolean b_ = false;
    /**
     * <code>bool b = 3;</code>
     * @return The b.
     */
    @java.lang.Override
    public boolean getB() {
      return b_;
    }

    public static final int DES_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object des_ = "";
    /**
     * <code>string des = 4;</code>
     * @return The des.
     */
    @java.lang.Override
    public java.lang.String getDes() {
      java.lang.Object ref = des_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        des_ = s;
        return s;
      }
    }
    /**
     * <code>string des = 4;</code>
     * @return The bytes for des.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDesBytes() {
      java.lang.Object ref = des_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        des_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (b_ != false) {
        output.writeBool(3, b_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(des_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, des_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (b_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, b_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(des_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, des_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xirui.protocol.BaseProtos.Msg1)) {
        return super.equals(obj);
      }
      com.xirui.protocol.BaseProtos.Msg1 other = (com.xirui.protocol.BaseProtos.Msg1) obj;

      if (getId()
          != other.getId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getB()
          != other.getB()) return false;
      if (!getDes()
          .equals(other.getDes())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getB());
      hash = (37 * hash) + DES_FIELD_NUMBER;
      hash = (53 * hash) + getDes().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xirui.protocol.BaseProtos.Msg1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xirui.protocol.BaseProtos.Msg1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xirui.protocol.BaseProtos.Msg1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xirui.protocol.BaseProtos.Msg1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xirui.protocol.BaseProtos.Msg1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xirui.protocol.BaseProtos.Msg1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xirui.protocol.BaseProtos.Msg1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xirui.protocol.BaseProtos.Msg1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.xirui.protocol.BaseProtos.Msg1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.xirui.protocol.BaseProtos.Msg1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xirui.protocol.BaseProtos.Msg1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xirui.protocol.BaseProtos.Msg1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xirui.protocol.BaseProtos.Msg1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xirui.protocol.Msg1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xirui.protocol.Msg1)
        com.xirui.protocol.BaseProtos.Msg1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xirui.protocol.BaseProtos.internal_static_com_xirui_protocol_Msg1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xirui.protocol.BaseProtos.internal_static_com_xirui_protocol_Msg1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xirui.protocol.BaseProtos.Msg1.class, com.xirui.protocol.BaseProtos.Msg1.Builder.class);
      }

      // Construct using com.xirui.protocol.BaseProtos.Msg1.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        content_ = "";
        b_ = false;
        des_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xirui.protocol.BaseProtos.internal_static_com_xirui_protocol_Msg1_descriptor;
      }

      @java.lang.Override
      public com.xirui.protocol.BaseProtos.Msg1 getDefaultInstanceForType() {
        return com.xirui.protocol.BaseProtos.Msg1.getDefaultInstance();
      }

      @java.lang.Override
      public com.xirui.protocol.BaseProtos.Msg1 build() {
        com.xirui.protocol.BaseProtos.Msg1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xirui.protocol.BaseProtos.Msg1 buildPartial() {
        com.xirui.protocol.BaseProtos.Msg1 result = new com.xirui.protocol.BaseProtos.Msg1(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.xirui.protocol.BaseProtos.Msg1 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.b_ = b_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.des_ = des_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xirui.protocol.BaseProtos.Msg1) {
          return mergeFrom((com.xirui.protocol.BaseProtos.Msg1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xirui.protocol.BaseProtos.Msg1 other) {
        if (other == com.xirui.protocol.BaseProtos.Msg1.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getB() != false) {
          setB(other.getB());
        }
        if (!other.getDes().isEmpty()) {
          des_ = other.des_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                b_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                des_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       * 字段格式为：限定修饰符 数据类型 字段名称(建议以_分隔) = 分配标识号(同一消息结构体中不能重复，无须连续，开始使用就不能再改变)
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * 字段格式为：限定修饰符 数据类型 字段名称(建议以_分隔) = 分配标识号(同一消息结构体中不能重复，无须连续，开始使用就不能再改变)
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字段格式为：限定修饰符 数据类型 字段名称(建议以_分隔) = 分配标识号(同一消息结构体中不能重复，无须连续，开始使用就不能再改变)
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 2;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private boolean b_ ;
      /**
       * <code>bool b = 3;</code>
       * @return The b.
       */
      @java.lang.Override
      public boolean getB() {
        return b_;
      }
      /**
       * <code>bool b = 3;</code>
       * @param value The b to set.
       * @return This builder for chaining.
       */
      public Builder setB(boolean value) {

        b_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool b = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearB() {
        bitField0_ = (bitField0_ & ~0x00000004);
        b_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object des_ = "";
      /**
       * <code>string des = 4;</code>
       * @return The des.
       */
      public java.lang.String getDes() {
        java.lang.Object ref = des_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          des_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string des = 4;</code>
       * @return The bytes for des.
       */
      public com.google.protobuf.ByteString
          getDesBytes() {
        java.lang.Object ref = des_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          des_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string des = 4;</code>
       * @param value The des to set.
       * @return This builder for chaining.
       */
      public Builder setDes(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        des_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string des = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDes() {
        des_ = getDefaultInstance().getDes();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string des = 4;</code>
       * @param value The bytes for des to set.
       * @return This builder for chaining.
       */
      public Builder setDesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        des_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xirui.protocol.Msg1)
    }

    // @@protoc_insertion_point(class_scope:com.xirui.protocol.Msg1)
    private static final com.xirui.protocol.BaseProtos.Msg1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xirui.protocol.BaseProtos.Msg1();
    }

    public static com.xirui.protocol.BaseProtos.Msg1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg1>
        PARSER = new com.google.protobuf.AbstractParser<Msg1>() {
      @java.lang.Override
      public Msg1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Msg1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg1> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xirui.protocol.BaseProtos.Msg1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xirui_protocol_BaseMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xirui_protocol_BaseMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xirui_protocol_Msg1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xirui_protocol_Msg1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rBaseMsg.proto\022\022com.xirui.protocol\">\n\007B" +
      "aseMsg\022\014\n\004type\030\001 \001(\r\022%\n\003msg\030\002 \001(\0132\030.com." +
      "xirui.protocol.Msg1\";\n\004Msg1\022\n\n\002id\030\001 \001(\r\022" +
      "\017\n\007content\030\002 \001(\t\022\t\n\001b\030\003 \001(\010\022\013\n\003des\030\004 \001(\t" +
      "B\"\n\022com.xirui.protocolB\nBaseProtosP\000b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_xirui_protocol_BaseMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xirui_protocol_BaseMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xirui_protocol_BaseMsg_descriptor,
        new java.lang.String[] { "Type", "Msg", });
    internal_static_com_xirui_protocol_Msg1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xirui_protocol_Msg1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xirui_protocol_Msg1_descriptor,
        new java.lang.String[] { "Id", "Content", "B", "Des", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
